-- CreateTable
CREATE TABLE "Sag" (
    "id" INTEGER NOT NULL,
    "typeid" INTEGER NOT NULL,
    "kategoriid" INTEGER,
    "statusid" INTEGER NOT NULL,
    "titel" TEXT,
    "titelkort" TEXT,
    "offentlighedskode" TEXT,
    "nummer" TEXT,
    "nummerprefix" TEXT,
    "nummernumerisk" TEXT,
    "nummerpostfix" TEXT,
    "resume" TEXT,
    "afstemningskonklusion" TEXT,
    "periodeid" INTEGER NOT NULL,
    "afgoerelsesresultatkode" TEXT,
    "baggrundsmateriale" TEXT,
    "opdateringsdato" TIMESTAMP(3) NOT NULL,
    "statsbudgetsag" BOOLEAN NOT NULL,
    "begrundelse" TEXT,
    "paragrafnummer" INTEGER,
    "paragraf" TEXT,
    "afgoerelsesdato" TIMESTAMP(3),
    "afgorelse" TEXT,
    "lovnummer" TEXT,
    "lovnummerdato" TIMESTAMP(3),
    "retsinformationsurl" TEXT,
    "fremsatundersagid" INTEGER,
    "deltundersagid" INTEGER,

    CONSTRAINT "Sag_pkey" PRIMARY KEY ("id")
);
